name: 'Regex Match Commenter Action'
description: 'Searches for regex patterns in PR diffs and comments on them'
author: 'Zumba'

branding:
  icon: 'heart'
  color: 'red'

inputs:
  regex_patterns:
    description: 'List of regex patterns to search for'
    required: true

  diff_scope:
    description: 'Scope of the search (added, removed, both)'
    required: false
    default: 'both'

  mark_changes_requested:
    description: 'Mark PR as changes requested if matches are found'
    required: false
    default: 'false'

  match_found_message:
    description: 'Comment message for a regex match'
    required: false
    default: 'Regex match found.'

  no_match_found_message:
    description: 'Comment message when no regex matches are found'
    required: false
    default: 'No regex matches found in the diff.'

  changes_requested_message:
    description: 'Message for marking PR as changes requested'
    required: false
    default: 'Changes are requested due to regex match.'

runs:
  using: node20
  main: dist/index.js
